/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID cad17)
#  Generated on:      Fri Mar 22 01:20:30 2024
#  Design:            CHIP
#  Command:           saveNetlist CHIP.v
###############################################################
*/
module alu_DW01_sub_0 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO, 
	FE_DBTN17_out_inst_3_4, 
	FE_DBTN18_out_inst_3_5, 
	FE_DBTN16_out_inst_3_3, 
	FE_DBTN13_out_inst_3_0, 
	FE_DBTN15_out_inst_3_2, 
	FE_DBTN14_out_inst_3_1);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] DIFF;
   output CO;
   input FE_DBTN17_out_inst_3_4;
   input FE_DBTN18_out_inst_3_5;
   input FE_DBTN16_out_inst_3_3;
   input FE_DBTN13_out_inst_3_0;
   input FE_DBTN15_out_inst_3_2;
   input FE_DBTN14_out_inst_3_1;

   // Internal wires
   wire n1;
   wire n9;
   wire [9:0] carry;

   FA1S U2_6 (.S(DIFF[6]),
	.CO(carry[7]),
	.A(A[6]),
	.B(FE_DBTN18_out_inst_3_5),
	.CI(carry[6]));
   FA1S U2_5 (.S(DIFF[5]),
	.CO(carry[6]),
	.A(A[5]),
	.B(FE_DBTN17_out_inst_3_4),
	.CI(carry[5]));
   FA1S U2_4 (.S(DIFF[4]),
	.CO(carry[5]),
	.A(A[4]),
	.B(FE_DBTN16_out_inst_3_3),
	.CI(carry[4]));
   FA1S U2_3 (.S(DIFF[3]),
	.CO(carry[4]),
	.A(A[3]),
	.B(FE_DBTN15_out_inst_3_2),
	.CI(carry[3]));
   FA1S U2_2 (.S(DIFF[2]),
	.CO(carry[3]),
	.A(A[2]),
	.B(FE_DBTN14_out_inst_3_1),
	.CI(carry[2]));
   FA1S U2_1 (.S(DIFF[1]),
	.CO(carry[2]),
	.A(A[1]),
	.B(FE_DBTN13_out_inst_3_0),
	.CI(carry[1]));
   FA1S U2_7 (.S(DIFF[7]),
	.CO(carry[8]),
	.A(A[7]),
	.B(B[7]),
	.CI(carry[7]));
   INV1S U2 (.O(n9),
	.I(B[0]));
   INV1S U4 (.O(n1),
	.I(A[0]));
   XNR2HS U10 (.O(DIFF[0]),
	.I1(n9),
	.I2(A[0]));
   ND2 U11 (.O(carry[1]),
	.I1(B[0]),
	.I2(n1));
   INV1S U12 (.O(DIFF[8]),
	.I(carry[8]));
endmodule

module alu_DW01_add_0 (
	A, 
	B, 
	CI, 
	SUM, 
	CO);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] SUM;
   output CO;

   // Internal wires
   wire n1;
   wire [8:1] carry;

   FA1S U1_1 (.S(SUM[1]),
	.CO(carry[2]),
	.A(A[1]),
	.B(B[1]),
	.CI(n1));
   FA1S U1_7 (.S(SUM[7]),
	.CO(SUM[8]),
	.A(A[7]),
	.B(B[7]),
	.CI(carry[7]));
   FA1S U1_6 (.S(SUM[6]),
	.CO(carry[7]),
	.A(A[6]),
	.B(B[6]),
	.CI(carry[6]));
   FA1S U1_5 (.S(SUM[5]),
	.CO(carry[6]),
	.A(A[5]),
	.B(B[5]),
	.CI(carry[5]));
   FA1S U1_4 (.S(SUM[4]),
	.CO(carry[5]),
	.A(A[4]),
	.B(B[4]),
	.CI(carry[4]));
   FA1S U1_3 (.S(SUM[3]),
	.CO(carry[4]),
	.A(A[3]),
	.B(B[3]),
	.CI(carry[3]));
   FA1S U1_2 (.S(SUM[2]),
	.CO(carry[3]),
	.A(A[2]),
	.B(B[2]),
	.CI(carry[2]));
   AN2 U1 (.O(n1),
	.I1(B[0]),
	.I2(A[0]));
endmodule

module alu_DW_mult_uns_0 (
	a, 
	b, 
	product);
   input [7:0] a;
   input [7:0] b;
   output [15:0] product;

   // Internal wires
   wire FE_OFN69_n247;
   wire FE_OFN68_n241;
   wire FE_OFN13_FE_DBTN5_out_inst_3_7;
   wire FE_OFN12_FE_DBTN6_reg_data_b_1;
   wire FE_OFN11_FE_DBTN7_reg_data_b_2;
   wire FE_OFN10_FE_DBTN8_reg_data_b_3;
   wire FE_OFN9_FE_DBTN9_reg_data_b_4;
   wire FE_OFN8_FE_DBTN10_reg_data_b_5;
   wire FE_OFN7_FE_DBTN11_reg_data_b_6;
   wire FE_OFN6_FE_DBTN12_reg_data_b_7;
   wire FE_OFN5_FE_DBTN13_out_inst_3_0;
   wire FE_OFN4_FE_DBTN14_out_inst_3_1;
   wire FE_OFN3_FE_DBTN15_out_inst_3_2;
   wire FE_OFN2_FE_DBTN16_out_inst_3_3;
   wire FE_OFN1_FE_DBTN17_out_inst_3_4;
   wire FE_OFN0_FE_DBTN18_out_inst_3_5;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n241;
   wire n247;

   BUF1 FE_OFC69_n247 (.O(FE_OFN69_n247),
	.I(n247));
   BUF1 FE_OFC68_n241 (.O(FE_OFN68_n241),
	.I(n241));
   BUF1 FE_OFC13_FE_DBTN5_out_inst_3_7 (.O(FE_OFN13_FE_DBTN5_out_inst_3_7),
	.I(a[7]));
   BUF1 FE_OFC12_FE_DBTN6_reg_data_b_1 (.O(FE_OFN12_FE_DBTN6_reg_data_b_1),
	.I(b[1]));
   BUF1 FE_OFC11_FE_DBTN7_reg_data_b_2 (.O(FE_OFN11_FE_DBTN7_reg_data_b_2),
	.I(b[2]));
   BUF1 FE_OFC10_FE_DBTN8_reg_data_b_3 (.O(FE_OFN10_FE_DBTN8_reg_data_b_3),
	.I(b[3]));
   BUF1 FE_OFC9_FE_DBTN9_reg_data_b_4 (.O(FE_OFN9_FE_DBTN9_reg_data_b_4),
	.I(b[4]));
   BUF1 FE_OFC8_FE_DBTN10_reg_data_b_5 (.O(FE_OFN8_FE_DBTN10_reg_data_b_5),
	.I(b[5]));
   BUF1 FE_OFC7_FE_DBTN11_reg_data_b_6 (.O(FE_OFN7_FE_DBTN11_reg_data_b_6),
	.I(b[6]));
   BUF1 FE_OFC6_FE_DBTN12_reg_data_b_7 (.O(FE_OFN6_FE_DBTN12_reg_data_b_7),
	.I(b[7]));
   BUF1 FE_OFC5_FE_DBTN13_out_inst_3_0 (.O(FE_OFN5_FE_DBTN13_out_inst_3_0),
	.I(a[1]));
   BUF1 FE_OFC4_FE_DBTN14_out_inst_3_1 (.O(FE_OFN4_FE_DBTN14_out_inst_3_1),
	.I(a[2]));
   BUF1 FE_OFC3_FE_DBTN15_out_inst_3_2 (.O(FE_OFN3_FE_DBTN15_out_inst_3_2),
	.I(a[3]));
   BUF1 FE_OFC2_FE_DBTN16_out_inst_3_3 (.O(FE_OFN2_FE_DBTN16_out_inst_3_3),
	.I(a[4]));
   BUF1 FE_OFC1_FE_DBTN17_out_inst_3_4 (.O(FE_OFN1_FE_DBTN17_out_inst_3_4),
	.I(a[5]));
   BUF1 FE_OFC0_FE_DBTN18_out_inst_3_5 (.O(FE_OFN0_FE_DBTN18_out_inst_3_5),
	.I(a[6]));
   FA1S U2 (.S(product[14]),
	.CO(product[15]),
	.A(n99),
	.B(n15),
	.CI(n2));
   FA1S U3 (.S(product[13]),
	.CO(n2),
	.A(n16),
	.B(n17),
	.CI(n3));
   FA1S U4 (.S(product[12]),
	.CO(n3),
	.A(n18),
	.B(n21),
	.CI(n4));
   FA1S U5 (.S(product[11]),
	.CO(n4),
	.A(n27),
	.B(n22),
	.CI(n5));
   FA1S U6 (.S(product[10]),
	.CO(n5),
	.A(n35),
	.B(n28),
	.CI(n6));
   FA1S U7 (.S(product[9]),
	.CO(n6),
	.A(n45),
	.B(n36),
	.CI(n7));
   FA1S U8 (.S(product[8]),
	.CO(n7),
	.A(n57),
	.B(n46),
	.CI(n8));
   FA1S U9 (.S(product[7]),
	.CO(n8),
	.A(n69),
	.B(n58),
	.CI(n9));
   FA1S U10 (.S(product[6]),
	.CO(n9),
	.A(n79),
	.B(n70),
	.CI(n10));
   FA1S U11 (.S(product[5]),
	.CO(n10),
	.A(n87),
	.B(n80),
	.CI(n11));
   FA1S U12 (.S(product[4]),
	.CO(n11),
	.A(n93),
	.B(n88),
	.CI(n12));
   FA1S U13 (.S(product[3]),
	.CO(n12),
	.A(n96),
	.B(n13),
	.CI(n94));
   FA1S U14 (.S(product[2]),
	.CO(n13),
	.A(n146),
	.B(n14),
	.CI(n98));
   HA1 U15 (.S(product[1]),
	.C(n14),
	.A(n154),
	.B(n161));
   FA1S U16 (.S(n16),
	.CO(n15),
	.A(n107),
	.B(n100),
	.CI(n19));
   FA1S U17 (.S(n18),
	.CO(n17),
	.A(n25),
	.B(n20),
	.CI(n23));
   FA1S U18 (.S(n20),
	.CO(n19),
	.A(n115),
	.B(n101),
	.CI(n108));
   FA1S U19 (.S(n22),
	.CO(n21),
	.A(n31),
	.B(n24),
	.CI(n29));
   FA1S U20 (.S(n24),
	.CO(n23),
	.A(n116),
	.B(n33),
	.CI(n26));
   FA1S U21 (.S(n26),
	.CO(n25),
	.A(n123),
	.B(n102),
	.CI(n109));
   FA1S U22 (.S(n28),
	.CO(n27),
	.A(n32),
	.B(n37),
	.CI(n30));
   FA1S U23 (.S(n30),
	.CO(n29),
	.A(n41),
	.B(n34),
	.CI(n39));
   FA1S U24 (.S(n32),
	.CO(n31),
	.A(n124),
	.B(n117),
	.CI(n43));
   FA1S U25 (.S(n34),
	.CO(n33),
	.A(n131),
	.B(n103),
	.CI(n110));
   FA1S U26 (.S(n36),
	.CO(n35),
	.A(n40),
	.B(n47),
	.CI(n38));
   FA1S U27 (.S(n38),
	.CO(n37),
	.A(n44),
	.B(n51),
	.CI(n49));
   FA1S U28 (.S(n40),
	.CO(n39),
	.A(n55),
	.B(n53),
	.CI(n42));
   FA1S U29 (.S(n42),
	.CO(n41),
	.A(n118),
	.B(n125),
	.CI(n132));
   FA1S U30 (.S(n44),
	.CO(n43),
	.A(n139),
	.B(n104),
	.CI(n111));
   FA1S U31 (.S(n46),
	.CO(n45),
	.A(n50),
	.B(n59),
	.CI(n48));
   FA1S U32 (.S(n48),
	.CO(n47),
	.A(n54),
	.B(n52),
	.CI(n61));
   FA1S U33 (.S(n50),
	.CO(n49),
	.A(n56),
	.B(n65),
	.CI(n63));
   FA1S U34 (.S(n52),
	.CO(n51),
	.A(n140),
	.B(n133),
	.CI(n67));
   FA1S U35 (.S(n54),
	.CO(n53),
	.A(n126),
	.B(n119),
	.CI(n147));
   HA1 U36 (.S(n56),
	.C(n55),
	.A(n112),
	.B(n105));
   FA1S U37 (.S(n58),
	.CO(n57),
	.A(n71),
	.B(n62),
	.CI(n60));
   FA1S U38 (.S(n60),
	.CO(n59),
	.A(n64),
	.B(n66),
	.CI(n73));
   FA1S U39 (.S(n62),
	.CO(n61),
	.A(n77),
	.B(n68),
	.CI(n75));
   FA1S U40 (.S(n64),
	.CO(n63),
	.A(n141),
	.B(n127),
	.CI(n134));
   FA1S U41 (.S(n66),
	.CO(n65),
	.A(n155),
	.B(n120),
	.CI(n148));
   HA1 U42 (.S(n68),
	.C(n67),
	.A(n113),
	.B(n106));
   FA1S U43 (.S(n70),
	.CO(n69),
	.A(n81),
	.B(n74),
	.CI(n72));
   FA1S U44 (.S(n72),
	.CO(n71),
	.A(n78),
	.B(n83),
	.CI(n76));
   FA1S U45 (.S(n74),
	.CO(n73),
	.A(n142),
	.B(n135),
	.CI(n85));
   FA1S U46 (.S(n76),
	.CO(n75),
	.A(n156),
	.B(n128),
	.CI(n149));
   HA1 U47 (.S(n78),
	.C(n77),
	.A(n121),
	.B(n114));
   FA1S U48 (.S(n80),
	.CO(n79),
	.A(n89),
	.B(n84),
	.CI(n82));
   FA1S U49 (.S(n82),
	.CO(n81),
	.A(n150),
	.B(n91),
	.CI(n86));
   FA1S U50 (.S(n84),
	.CO(n83),
	.A(n157),
	.B(n136),
	.CI(n143));
   HA1 U51 (.S(n86),
	.C(n85),
	.A(n129),
	.B(n122));
   FA1S U52 (.S(n88),
	.CO(n87),
	.A(n95),
	.B(n92),
	.CI(n90));
   FA1S U53 (.S(n90),
	.CO(n89),
	.A(n158),
	.B(n144),
	.CI(n151));
   HA1 U54 (.S(n92),
	.C(n91),
	.A(n137),
	.B(n130));
   FA1S U55 (.S(n94),
	.CO(n93),
	.A(n159),
	.B(n152),
	.CI(n97));
   HA1 U56 (.S(n96),
	.C(n95),
	.A(n145),
	.B(n138));
   HA1 U57 (.S(n98),
	.C(n97),
	.A(n160),
	.B(n153));
   INV1S U164 (.O(n247),
	.I(a[0]));
   INV1S U166 (.O(n241),
	.I(b[0]));
   NR2 U174 (.O(product[0]),
	.I1(n247),
	.I2(n241));
   NR2 U175 (.O(n99),
	.I1(FE_OFN13_FE_DBTN5_out_inst_3_7),
	.I2(b[7]));
   NR2 U176 (.O(n161),
	.I1(n247),
	.I2(b[1]));
   NR2 U177 (.O(n160),
	.I1(n247),
	.I2(b[2]));
   NR2 U178 (.O(n159),
	.I1(n247),
	.I2(b[3]));
   NR2 U179 (.O(n158),
	.I1(FE_OFN69_n247),
	.I2(b[4]));
   NR2 U180 (.O(n157),
	.I1(FE_OFN69_n247),
	.I2(b[5]));
   NR2 U181 (.O(n156),
	.I1(FE_OFN69_n247),
	.I2(b[6]));
   NR2 U182 (.O(n155),
	.I1(FE_OFN69_n247),
	.I2(FE_OFN6_FE_DBTN12_reg_data_b_7));
   NR2 U183 (.O(n154),
	.I1(FE_OFN68_n241),
	.I2(FE_OFN5_FE_DBTN13_out_inst_3_0));
   NR2 U184 (.O(n153),
	.I1(b[1]),
	.I2(FE_OFN5_FE_DBTN13_out_inst_3_0));
   NR2 U185 (.O(n152),
	.I1(b[2]),
	.I2(FE_OFN5_FE_DBTN13_out_inst_3_0));
   NR2 U186 (.O(n151),
	.I1(b[3]),
	.I2(FE_OFN5_FE_DBTN13_out_inst_3_0));
   NR2 U187 (.O(n150),
	.I1(b[4]),
	.I2(FE_OFN5_FE_DBTN13_out_inst_3_0));
   NR2 U188 (.O(n149),
	.I1(b[5]),
	.I2(a[1]));
   NR2 U189 (.O(n148),
	.I1(b[6]),
	.I2(a[1]));
   NR2 U190 (.O(n147),
	.I1(FE_OFN6_FE_DBTN12_reg_data_b_7),
	.I2(a[1]));
   NR2 U191 (.O(n146),
	.I1(FE_OFN68_n241),
	.I2(FE_OFN4_FE_DBTN14_out_inst_3_1));
   NR2 U192 (.O(n145),
	.I1(FE_OFN12_FE_DBTN6_reg_data_b_1),
	.I2(FE_OFN4_FE_DBTN14_out_inst_3_1));
   NR2 U193 (.O(n144),
	.I1(FE_OFN11_FE_DBTN7_reg_data_b_2),
	.I2(FE_OFN4_FE_DBTN14_out_inst_3_1));
   NR2 U194 (.O(n143),
	.I1(FE_OFN10_FE_DBTN8_reg_data_b_3),
	.I2(FE_OFN4_FE_DBTN14_out_inst_3_1));
   NR2 U195 (.O(n142),
	.I1(FE_OFN9_FE_DBTN9_reg_data_b_4),
	.I2(FE_OFN4_FE_DBTN14_out_inst_3_1));
   NR2 U196 (.O(n141),
	.I1(FE_OFN8_FE_DBTN10_reg_data_b_5),
	.I2(a[2]));
   NR2 U197 (.O(n140),
	.I1(FE_OFN7_FE_DBTN11_reg_data_b_6),
	.I2(a[2]));
   NR2 U198 (.O(n139),
	.I1(FE_OFN6_FE_DBTN12_reg_data_b_7),
	.I2(FE_OFN4_FE_DBTN14_out_inst_3_1));
   NR2 U199 (.O(n138),
	.I1(FE_OFN68_n241),
	.I2(FE_OFN3_FE_DBTN15_out_inst_3_2));
   NR2 U200 (.O(n137),
	.I1(FE_OFN12_FE_DBTN6_reg_data_b_1),
	.I2(FE_OFN3_FE_DBTN15_out_inst_3_2));
   NR2 U201 (.O(n136),
	.I1(FE_OFN11_FE_DBTN7_reg_data_b_2),
	.I2(FE_OFN3_FE_DBTN15_out_inst_3_2));
   NR2 U202 (.O(n135),
	.I1(FE_OFN10_FE_DBTN8_reg_data_b_3),
	.I2(FE_OFN3_FE_DBTN15_out_inst_3_2));
   NR2 U203 (.O(n134),
	.I1(FE_OFN9_FE_DBTN9_reg_data_b_4),
	.I2(a[3]));
   NR2 U204 (.O(n133),
	.I1(FE_OFN8_FE_DBTN10_reg_data_b_5),
	.I2(a[3]));
   NR2 U205 (.O(n132),
	.I1(FE_OFN7_FE_DBTN11_reg_data_b_6),
	.I2(FE_OFN3_FE_DBTN15_out_inst_3_2));
   NR2 U206 (.O(n131),
	.I1(FE_OFN6_FE_DBTN12_reg_data_b_7),
	.I2(FE_OFN3_FE_DBTN15_out_inst_3_2));
   NR2 U207 (.O(n130),
	.I1(FE_OFN68_n241),
	.I2(a[4]));
   NR2 U208 (.O(n129),
	.I1(FE_OFN12_FE_DBTN6_reg_data_b_1),
	.I2(a[4]));
   NR2 U209 (.O(n128),
	.I1(FE_OFN11_FE_DBTN7_reg_data_b_2),
	.I2(a[4]));
   NR2 U210 (.O(n127),
	.I1(FE_OFN10_FE_DBTN8_reg_data_b_3),
	.I2(a[4]));
   NR2 U211 (.O(n126),
	.I1(FE_OFN9_FE_DBTN9_reg_data_b_4),
	.I2(FE_OFN2_FE_DBTN16_out_inst_3_3));
   NR2 U212 (.O(n125),
	.I1(FE_OFN8_FE_DBTN10_reg_data_b_5),
	.I2(FE_OFN2_FE_DBTN16_out_inst_3_3));
   NR2 U213 (.O(n124),
	.I1(FE_OFN7_FE_DBTN11_reg_data_b_6),
	.I2(FE_OFN2_FE_DBTN16_out_inst_3_3));
   NR2 U214 (.O(n123),
	.I1(FE_OFN6_FE_DBTN12_reg_data_b_7),
	.I2(FE_OFN2_FE_DBTN16_out_inst_3_3));
   NR2 U215 (.O(n122),
	.I1(FE_OFN68_n241),
	.I2(a[5]));
   NR2 U216 (.O(n121),
	.I1(FE_OFN12_FE_DBTN6_reg_data_b_1),
	.I2(a[5]));
   NR2 U217 (.O(n120),
	.I1(FE_OFN11_FE_DBTN7_reg_data_b_2),
	.I2(a[5]));
   NR2 U218 (.O(n119),
	.I1(FE_OFN10_FE_DBTN8_reg_data_b_3),
	.I2(a[5]));
   NR2 U219 (.O(n118),
	.I1(FE_OFN9_FE_DBTN9_reg_data_b_4),
	.I2(FE_OFN1_FE_DBTN17_out_inst_3_4));
   NR2 U220 (.O(n117),
	.I1(FE_OFN8_FE_DBTN10_reg_data_b_5),
	.I2(FE_OFN1_FE_DBTN17_out_inst_3_4));
   NR2 U221 (.O(n116),
	.I1(FE_OFN7_FE_DBTN11_reg_data_b_6),
	.I2(FE_OFN1_FE_DBTN17_out_inst_3_4));
   NR2 U222 (.O(n115),
	.I1(b[7]),
	.I2(FE_OFN1_FE_DBTN17_out_inst_3_4));
   NR2 U223 (.O(n114),
	.I1(n241),
	.I2(a[6]));
   NR2 U224 (.O(n113),
	.I1(FE_OFN12_FE_DBTN6_reg_data_b_1),
	.I2(a[6]));
   NR2 U225 (.O(n112),
	.I1(FE_OFN11_FE_DBTN7_reg_data_b_2),
	.I2(FE_OFN0_FE_DBTN18_out_inst_3_5));
   NR2 U226 (.O(n111),
	.I1(FE_OFN10_FE_DBTN8_reg_data_b_3),
	.I2(FE_OFN0_FE_DBTN18_out_inst_3_5));
   NR2 U227 (.O(n110),
	.I1(FE_OFN9_FE_DBTN9_reg_data_b_4),
	.I2(FE_OFN0_FE_DBTN18_out_inst_3_5));
   NR2 U228 (.O(n109),
	.I1(FE_OFN8_FE_DBTN10_reg_data_b_5),
	.I2(FE_OFN0_FE_DBTN18_out_inst_3_5));
   NR2 U229 (.O(n108),
	.I1(FE_OFN7_FE_DBTN11_reg_data_b_6),
	.I2(FE_OFN0_FE_DBTN18_out_inst_3_5));
   NR2 U230 (.O(n107),
	.I1(b[7]),
	.I2(FE_OFN0_FE_DBTN18_out_inst_3_5));
   NR2 U231 (.O(n106),
	.I1(n241),
	.I2(a[7]));
   NR2 U232 (.O(n105),
	.I1(a[7]),
	.I2(FE_OFN12_FE_DBTN6_reg_data_b_1));
   NR2 U233 (.O(n104),
	.I1(FE_OFN13_FE_DBTN5_out_inst_3_7),
	.I2(FE_OFN11_FE_DBTN7_reg_data_b_2));
   NR2 U234 (.O(n103),
	.I1(FE_OFN13_FE_DBTN5_out_inst_3_7),
	.I2(FE_OFN10_FE_DBTN8_reg_data_b_3));
   NR2 U235 (.O(n102),
	.I1(FE_OFN13_FE_DBTN5_out_inst_3_7),
	.I2(FE_OFN9_FE_DBTN9_reg_data_b_4));
   NR2 U236 (.O(n101),
	.I1(FE_OFN13_FE_DBTN5_out_inst_3_7),
	.I2(FE_OFN8_FE_DBTN10_reg_data_b_5));
   NR2 U237 (.O(n100),
	.I1(FE_OFN13_FE_DBTN5_out_inst_3_7),
	.I2(FE_OFN7_FE_DBTN11_reg_data_b_6));
endmodule

module alu (
	clk_p_i, 
	reset_n_i, 
	data_a_i, 
	data_b_i, 
	inst_i, 
	data_o);
   input clk_p_i;
   input reset_n_i;
   input [7:0] data_a_i;
   input [7:0] data_b_i;
   input [2:0] inst_i;
   output [15:0] data_o;

   // Internal wires
   wire CTS_8;
   wire CTS_7;
   wire FE_OFN67_n55;
   wire FE_OFN66_n49;
   wire FE_OFN65_n46;
   wire FE_OFN64_n46;
   wire FE_OFN63_n46;
   wire FE_OFN62_n46;
   wire FE_OFN30_i_reset_n_i;
   wire FE_OFN29_i_reset_n_i;
   wire FE_OFN27_i_reset_n_i;
   wire FE_OFN26_i_reset_n_i;
   wire FE_OFN25_i_reset_n_i;
   wire FE_OFN24_i_reset_n_i;
   wire FE_OFN23_i_reset_n_i;
   wire FE_OFN21_i_inst_i_2;
   wire FE_OFN20_FE_DBTN0_n56;
   wire FE_OFN19_FE_DBTN1_n45;
   wire FE_OFN18_FE_DBTN2_n39;
   wire FE_OFN17_FE_DBTN2_n39;
   wire FE_OFN16_FE_DBTN2_n39;
   wire FE_OFN15_FE_DBTN3_n37;
   wire FE_OFN14_FE_DBTN4_n31;
   wire FE_DBTN18_out_inst_3_5;
   wire FE_DBTN17_out_inst_3_4;
   wire FE_DBTN16_out_inst_3_3;
   wire FE_DBTN15_out_inst_3_2;
   wire FE_DBTN14_out_inst_3_1;
   wire FE_DBTN13_out_inst_3_0;
   wire FE_DBTN12_reg_data_b_7;
   wire FE_DBTN11_reg_data_b_6;
   wire FE_DBTN10_reg_data_b_5;
   wire FE_DBTN9_reg_data_b_4;
   wire FE_DBTN8_reg_data_b_3;
   wire FE_DBTN7_reg_data_b_2;
   wire FE_DBTN6_reg_data_b_1;
   wire FE_DBTN5_out_inst_3_7;
   wire FE_DBTN4_n31;
   wire FE_DBTN3_n37;
   wire FE_DBTN2_n39;
   wire FE_DBTN1_n45;
   wire FE_DBTN0_n56;
   wire out_inst_1_15;
   wire out_inst_3_7;
   wire \reg_data_a[0] ;
   wire N102;
   wire N103;
   wire N104;
   wire N105;
   wire N106;
   wire N107;
   wire N108;
   wire N109;
   wire N116;
   wire n2;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire \add_103/A[0] ;
   wire \add_103/A[1] ;
   wire \add_103/A[2] ;
   wire \add_103/A[3] ;
   wire \add_103/A[4] ;
   wire \add_103/A[5] ;
   wire \add_103/A[6] ;
   wire \add_103/A[7] ;
   wire n116;
   wire n132;
   wire n133;
   wire n134;
   wire n137;
   wire n140;
   wire n141;
   wire [2:0] state;
   wire [15:0] ALU_out_inst;
   wire [8:0] out_inst_0;
   wire [7:0] out_inst_1;
   wire [15:0] out_inst_2;
   wire [5:0] out_inst_3;
   wire [7:0] reg_data_b;
   wire [15:2] \add_103/carry ;

   INV12CK CTS_ccl_a_INV_clk_p_i_G0_L3_1 (.O(CTS_7),
	.I(CTS_8));
   INV8CK CTS_ccl_a_INV_clk_p_i_G0_L2_1 (.O(CTS_8),
	.I(clk_p_i));
   BUF1 FE_OFC67_n55 (.O(FE_OFN67_n55),
	.I(n55));
   BUF1 FE_OFC66_n49 (.O(FE_OFN66_n49),
	.I(n49));
   INV1S FE_OFC65_n46 (.O(FE_OFN65_n46),
	.I(FE_OFN62_n46));
   INV1S FE_OFC64_n46 (.O(FE_OFN64_n46),
	.I(FE_OFN62_n46));
   BUF1 FE_OFC63_n46 (.O(FE_OFN63_n46),
	.I(n46));
   INV1S FE_OFC62_n46 (.O(FE_OFN62_n46),
	.I(n46));
   BUF1 FE_OFC30_i_reset_n_i (.O(FE_OFN30_i_reset_n_i),
	.I(FE_OFN29_i_reset_n_i));
   BUF1 FE_OFC29_i_reset_n_i (.O(FE_OFN29_i_reset_n_i),
	.I(FE_OFN26_i_reset_n_i));
   BUF1 FE_OFC27_i_reset_n_i (.O(FE_OFN27_i_reset_n_i),
	.I(FE_OFN24_i_reset_n_i));
   BUF1 FE_OFC26_i_reset_n_i (.O(FE_OFN26_i_reset_n_i),
	.I(FE_OFN23_i_reset_n_i));
   BUF1 FE_OFC25_i_reset_n_i (.O(FE_OFN25_i_reset_n_i),
	.I(FE_OFN23_i_reset_n_i));
   BUF1 FE_OFC24_i_reset_n_i (.O(FE_OFN24_i_reset_n_i),
	.I(FE_OFN23_i_reset_n_i));
   BUF1 FE_OFC23_i_reset_n_i (.O(FE_OFN23_i_reset_n_i),
	.I(reset_n_i));
   BUF1 FE_OFC21_i_inst_i_2 (.O(FE_OFN21_i_inst_i_2),
	.I(inst_i[2]));
   BUF1 FE_OFC20_FE_DBTN0_n56 (.O(FE_OFN20_FE_DBTN0_n56),
	.I(FE_DBTN0_n56));
   BUF1 FE_OFC19_FE_DBTN1_n45 (.O(FE_OFN19_FE_DBTN1_n45),
	.I(FE_DBTN1_n45));
   BUF1 FE_OFC18_FE_DBTN2_n39 (.O(FE_OFN18_FE_DBTN2_n39),
	.I(FE_OFN16_FE_DBTN2_n39));
   BUF1 FE_OFC17_FE_DBTN2_n39 (.O(FE_OFN17_FE_DBTN2_n39),
	.I(FE_OFN16_FE_DBTN2_n39));
   BUF1 FE_OFC16_FE_DBTN2_n39 (.O(FE_OFN16_FE_DBTN2_n39),
	.I(FE_DBTN2_n39));
   BUF1 FE_OFC15_FE_DBTN3_n37 (.O(FE_OFN15_FE_DBTN3_n37),
	.I(FE_DBTN3_n37));
   BUF1 FE_OFC14_FE_DBTN4_n31 (.O(FE_OFN14_FE_DBTN4_n31),
	.I(FE_DBTN4_n31));
   INV1S FE_DBTC18_out_inst_3_5 (.O(FE_DBTN18_out_inst_3_5),
	.I(out_inst_3[5]));
   INV1S FE_DBTC17_out_inst_3_4 (.O(FE_DBTN17_out_inst_3_4),
	.I(out_inst_3[4]));
   INV1S FE_DBTC16_out_inst_3_3 (.O(FE_DBTN16_out_inst_3_3),
	.I(out_inst_3[3]));
   INV1S FE_DBTC15_out_inst_3_2 (.O(FE_DBTN15_out_inst_3_2),
	.I(out_inst_3[2]));
   INV1S FE_DBTC14_out_inst_3_1 (.O(FE_DBTN14_out_inst_3_1),
	.I(out_inst_3[1]));
   INV1S FE_DBTC13_out_inst_3_0 (.O(FE_DBTN13_out_inst_3_0),
	.I(out_inst_3[0]));
   INV1S FE_DBTC12_reg_data_b_7 (.O(FE_DBTN12_reg_data_b_7),
	.I(reg_data_b[7]));
   INV1S FE_DBTC11_reg_data_b_6 (.O(FE_DBTN11_reg_data_b_6),
	.I(reg_data_b[6]));
   INV1S FE_DBTC10_reg_data_b_5 (.O(FE_DBTN10_reg_data_b_5),
	.I(reg_data_b[5]));
   INV1S FE_DBTC9_reg_data_b_4 (.O(FE_DBTN9_reg_data_b_4),
	.I(reg_data_b[4]));
   INV1S FE_DBTC8_reg_data_b_3 (.O(FE_DBTN8_reg_data_b_3),
	.I(reg_data_b[3]));
   INV1S FE_DBTC7_reg_data_b_2 (.O(FE_DBTN7_reg_data_b_2),
	.I(reg_data_b[2]));
   INV1S FE_DBTC6_reg_data_b_1 (.O(FE_DBTN6_reg_data_b_1),
	.I(reg_data_b[1]));
   INV1S FE_DBTC5_out_inst_3_7 (.O(FE_DBTN5_out_inst_3_7),
	.I(out_inst_3_7));
   INV1S FE_DBTC4_n31 (.O(FE_DBTN4_n31),
	.I(n31));
   INV1S FE_DBTC3_n37 (.O(FE_DBTN3_n37),
	.I(n37));
   INV1S FE_DBTC2_n39 (.O(FE_DBTN2_n39),
	.I(n39));
   INV1S FE_DBTC1_n45 (.O(FE_DBTN1_n45),
	.I(n45));
   INV1S FE_DBTC0_n56 (.O(FE_DBTN0_n56),
	.I(n56));
   ND2 U86 (.O(n26),
	.I1(n27),
	.I2(n29));
   ND2 U87 (.O(n32),
	.I1(FE_OFN21_i_inst_i_2),
	.I2(n35));
   ND2 U88 (.O(ALU_out_inst[9]),
	.I1(n44),
	.I2(FE_OFN19_FE_DBTN1_n45));
   ND2 U89 (.O(n47),
	.I1(out_inst_0[8]),
	.I2(n49));
   AO112 U90 (.O(ALU_out_inst[7]),
	.A1(n50),
	.B1(n51),
	.C1(out_inst_0[7]),
	.C2(n49));
   OR3B2 U91 (.O(ALU_out_inst[6]),
	.I1(n57),
	.B1(n58),
	.B2(n59));
   AO222 U92 (.O(n57),
	.A1(out_inst_2[6]),
	.A2(FE_OFN16_FE_DBTN2_n39),
	.B1(out_inst_3_7),
	.B2(FE_DBTN4_n31),
	.C1(out_inst_0[6]),
	.C2(n49));
   OR3B2 U93 (.O(ALU_out_inst[5]),
	.I1(n61),
	.B1(n62),
	.B2(n63));
   AO222 U94 (.O(n61),
	.A1(out_inst_2[5]),
	.A2(FE_OFN17_FE_DBTN2_n39),
	.B1(out_inst_3[5]),
	.B2(FE_OFN14_FE_DBTN4_n31),
	.C1(out_inst_0[5]),
	.C2(FE_OFN66_n49));
   OR3B2 U95 (.O(ALU_out_inst[4]),
	.I1(n65),
	.B1(n66),
	.B2(n67));
   AO222 U96 (.O(n65),
	.A1(out_inst_2[4]),
	.A2(FE_OFN17_FE_DBTN2_n39),
	.B1(out_inst_3[4]),
	.B2(FE_OFN14_FE_DBTN4_n31),
	.C1(out_inst_0[4]),
	.C2(FE_OFN66_n49));
   OR3B2 U97 (.O(ALU_out_inst[3]),
	.I1(n69),
	.B1(n70),
	.B2(n71));
   AO222 U98 (.O(n69),
	.A1(out_inst_2[3]),
	.A2(FE_OFN17_FE_DBTN2_n39),
	.B1(out_inst_3[3]),
	.B2(FE_OFN14_FE_DBTN4_n31),
	.C1(out_inst_0[3]),
	.C2(FE_OFN66_n49));
   OR3B2 U99 (.O(ALU_out_inst[2]),
	.I1(n73),
	.B1(n74),
	.B2(n75));
   AO222 U100 (.O(n73),
	.A1(out_inst_2[2]),
	.A2(FE_OFN17_FE_DBTN2_n39),
	.B1(out_inst_3[2]),
	.B2(FE_OFN14_FE_DBTN4_n31),
	.C1(out_inst_0[2]),
	.C2(FE_OFN66_n49));
   OR3B2 U101 (.O(ALU_out_inst[1]),
	.I1(n77),
	.B1(n78),
	.B2(n79));
   AO222 U102 (.O(n77),
	.A1(out_inst_2[1]),
	.A2(FE_OFN17_FE_DBTN2_n39),
	.B1(out_inst_3[1]),
	.B2(FE_OFN14_FE_DBTN4_n31),
	.C1(out_inst_0[1]),
	.C2(FE_OFN66_n49));
   ND2 U103 (.O(ALU_out_inst[15]),
	.I1(n81),
	.I2(FE_DBTN1_n45));
   ND2 U104 (.O(ALU_out_inst[14]),
	.I1(n82),
	.I2(FE_OFN19_FE_DBTN1_n45));
   ND2 U105 (.O(ALU_out_inst[13]),
	.I1(n83),
	.I2(FE_OFN19_FE_DBTN1_n45));
   ND2 U106 (.O(ALU_out_inst[12]),
	.I1(n84),
	.I2(FE_OFN19_FE_DBTN1_n45));
   ND2 U107 (.O(ALU_out_inst[11]),
	.I1(n85),
	.I2(FE_OFN19_FE_DBTN1_n45));
   ND2 U108 (.O(ALU_out_inst[10]),
	.I1(n86),
	.I2(FE_OFN19_FE_DBTN1_n45));
   OR3B2 U109 (.O(ALU_out_inst[0]),
	.I1(n88),
	.B1(n89),
	.B2(n90));
   AO222 U110 (.O(n88),
	.A1(out_inst_2[0]),
	.A2(FE_OFN17_FE_DBTN2_n39),
	.B1(out_inst_3[0]),
	.B2(FE_OFN14_FE_DBTN4_n31),
	.C1(n91),
	.C2(FE_OFN66_n49));
   alu_DW01_sub_0 sub_98 (.A({ n2,
		reg_data_b }),
	.B({ n2,
		FE_DBTN5_out_inst_3_7,
		out_inst_3,
		\reg_data_a[0]  }),
	.CI(n2),
	.DIFF({ out_inst_1_15,
		out_inst_1 }),
	.FE_DBTN17_out_inst_3_4(FE_DBTN17_out_inst_3_4),
	.FE_DBTN18_out_inst_3_5(FE_DBTN18_out_inst_3_5),
	.FE_DBTN16_out_inst_3_3(FE_DBTN16_out_inst_3_3),
	.FE_DBTN13_out_inst_3_0(FE_DBTN13_out_inst_3_0),
	.FE_DBTN15_out_inst_3_2(FE_DBTN15_out_inst_3_2),
	.FE_DBTN14_out_inst_3_1(FE_DBTN14_out_inst_3_1));
   alu_DW01_add_0 add_97 (.A({ n2,
		out_inst_3_7,
		out_inst_3,
		\reg_data_a[0]  }),
	.B({ n2,
		reg_data_b }),
	.CI(n2),
	.SUM(out_inst_0));
   alu_DW_mult_uns_0 mult_99 (.a({ FE_DBTN5_out_inst_3_7,
		FE_DBTN18_out_inst_3_5,
		FE_DBTN17_out_inst_3_4,
		FE_DBTN16_out_inst_3_3,
		FE_DBTN15_out_inst_3_2,
		FE_DBTN14_out_inst_3_1,
		FE_DBTN13_out_inst_3_0,
		\reg_data_a[0]  }),
	.b({ FE_DBTN12_reg_data_b_7,
		FE_DBTN11_reg_data_b_6,
		FE_DBTN10_reg_data_b_5,
		FE_DBTN9_reg_data_b_4,
		FE_DBTN8_reg_data_b_3,
		FE_DBTN7_reg_data_b_2,
		FE_DBTN6_reg_data_b_1,
		reg_data_b[0] }),
	.product(out_inst_2));
   HA1 \add_103/U1_1_1  (.S(N102),
	.C(\add_103/carry [2]),
	.A(\add_103/A[1] ),
	.B(\add_103/A[0] ));
   HA1 \add_103/U1_1_2  (.S(N103),
	.C(\add_103/carry [3]),
	.A(\add_103/A[2] ),
	.B(\add_103/carry [2]));
   HA1 \add_103/U1_1_3  (.S(N104),
	.C(\add_103/carry [4]),
	.A(\add_103/A[3] ),
	.B(\add_103/carry [3]));
   HA1 \add_103/U1_1_4  (.S(N105),
	.C(\add_103/carry [5]),
	.A(\add_103/A[4] ),
	.B(\add_103/carry [4]));
   HA1 \add_103/U1_1_5  (.S(N106),
	.C(\add_103/carry [6]),
	.A(\add_103/A[5] ),
	.B(\add_103/carry [5]));
   HA1 \add_103/U1_1_6  (.S(N107),
	.C(\add_103/carry [7]),
	.A(\add_103/A[6] ),
	.B(\add_103/carry [6]));
   HA1 \add_103/U1_1_7  (.S(N108),
	.C(\add_103/carry [8]),
	.A(\add_103/A[7] ),
	.B(\add_103/carry [7]));
   QDFFRBN \state_reg[0]  (.Q(state[0]),
	.D(n94),
	.CK(CTS_7),
	.RB(FE_OFN25_i_reset_n_i));
   QDFFRBN \state_reg[1]  (.Q(state[1]),
	.D(n92),
	.CK(CTS_7),
	.RB(FE_OFN25_i_reset_n_i));
   QDFFRBN \state_reg[2]  (.Q(state[2]),
	.D(n93),
	.CK(CTS_7),
	.RB(FE_OFN23_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[7]  (.Q(out_inst_3_7),
	.D(data_a_i[7]),
	.CK(CTS_7),
	.RB(FE_OFN24_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[7]  (.Q(reg_data_b[7]),
	.D(data_b_i[7]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[6]  (.Q(out_inst_3[5]),
	.D(data_a_i[6]),
	.CK(CTS_7),
	.RB(FE_OFN24_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[5]  (.Q(reg_data_b[5]),
	.D(data_b_i[5]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[6]  (.Q(reg_data_b[6]),
	.D(data_b_i[6]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[3]  (.Q(out_inst_3[2]),
	.D(data_a_i[3]),
	.CK(CTS_7),
	.RB(FE_OFN26_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[5]  (.Q(out_inst_3[4]),
	.D(data_a_i[5]),
	.CK(CTS_7),
	.RB(FE_OFN24_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[3]  (.Q(reg_data_b[3]),
	.D(data_b_i[3]),
	.CK(CTS_7),
	.RB(FE_OFN23_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[4]  (.Q(out_inst_3[3]),
	.D(data_a_i[4]),
	.CK(CTS_7),
	.RB(FE_OFN23_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[4]  (.Q(reg_data_b[4]),
	.D(data_b_i[4]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[2]  (.Q(out_inst_3[1]),
	.D(data_a_i[2]),
	.CK(CTS_7),
	.RB(FE_OFN26_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[0]  (.Q(reg_data_b[0]),
	.D(data_b_i[0]),
	.CK(CTS_7),
	.RB(FE_OFN27_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[1]  (.Q(reg_data_b[1]),
	.D(data_b_i[1]),
	.CK(CTS_7),
	.RB(FE_OFN27_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[2]  (.Q(reg_data_b[2]),
	.D(data_b_i[2]),
	.CK(CTS_7),
	.RB(FE_OFN27_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[1]  (.Q(out_inst_3[0]),
	.D(data_a_i[1]),
	.CK(CTS_7),
	.RB(FE_OFN26_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[0]  (.Q(\reg_data_a[0] ),
	.D(data_a_i[0]),
	.CK(CTS_7),
	.RB(FE_OFN26_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[1]  (.Q(data_o[1]),
	.D(ALU_out_inst[1]),
	.CK(CTS_7),
	.RB(FE_OFN24_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[0]  (.Q(data_o[0]),
	.D(ALU_out_inst[0]),
	.CK(CTS_7),
	.RB(FE_OFN27_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[8]  (.Q(data_o[8]),
	.D(ALU_out_inst[8]),
	.CK(CTS_7),
	.RB(FE_OFN29_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[9]  (.Q(data_o[9]),
	.D(ALU_out_inst[9]),
	.CK(CTS_7),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[6]  (.Q(data_o[6]),
	.D(ALU_out_inst[6]),
	.CK(CTS_7),
	.RB(FE_OFN29_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[5]  (.Q(data_o[5]),
	.D(ALU_out_inst[5]),
	.CK(CTS_7),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[4]  (.Q(data_o[4]),
	.D(ALU_out_inst[4]),
	.CK(CTS_7),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[3]  (.Q(data_o[3]),
	.D(ALU_out_inst[3]),
	.CK(CTS_7),
	.RB(FE_OFN27_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[2]  (.Q(data_o[2]),
	.D(ALU_out_inst[2]),
	.CK(CTS_7),
	.RB(FE_OFN27_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[7]  (.Q(data_o[7]),
	.D(ALU_out_inst[7]),
	.CK(CTS_7),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[10]  (.Q(data_o[10]),
	.D(ALU_out_inst[10]),
	.CK(CTS_7),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[11]  (.Q(data_o[11]),
	.D(ALU_out_inst[11]),
	.CK(CTS_7),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[12]  (.Q(data_o[12]),
	.D(ALU_out_inst[12]),
	.CK(CTS_7),
	.RB(FE_OFN29_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[13]  (.Q(data_o[13]),
	.D(ALU_out_inst[13]),
	.CK(CTS_7),
	.RB(FE_OFN29_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[15]  (.Q(data_o[15]),
	.D(ALU_out_inst[15]),
	.CK(CTS_7),
	.RB(FE_OFN26_i_reset_n_i));
   QDFFRBS \ALU_d2_r_reg[14]  (.Q(data_o[14]),
	.D(ALU_out_inst[14]),
	.CK(CTS_7),
	.RB(FE_OFN29_i_reset_n_i));
   NR2 U132 (.O(n116),
	.I1(\add_103/carry [8]),
	.I2(out_inst_1_15));
   OAI22S U134 (.O(n45),
	.A1(n132),
	.A2(n87),
	.B1(out_inst_1_15),
	.B2(n37));
   AOI22S U144 (.O(n82),
	.A1(N116),
	.A2(FE_OFN65_n46),
	.B1(out_inst_2[14]),
	.B2(FE_OFN18_FE_DBTN2_n39));
   AOI22S U145 (.O(n81),
	.A1(n116),
	.A2(FE_OFN65_n46),
	.B1(out_inst_2[15]),
	.B2(FE_OFN18_FE_DBTN2_n39));
   AOI22S U146 (.O(n83),
	.A1(N116),
	.A2(FE_OFN64_n46),
	.B1(out_inst_2[13]),
	.B2(FE_OFN18_FE_DBTN2_n39));
   AOI22S U147 (.O(n84),
	.A1(n116),
	.A2(FE_OFN65_n46),
	.B1(out_inst_2[12]),
	.B2(FE_OFN18_FE_DBTN2_n39));
   AOI22S U148 (.O(n85),
	.A1(N116),
	.A2(FE_OFN65_n46),
	.B1(out_inst_2[11]),
	.B2(FE_OFN18_FE_DBTN2_n39));
   AOI22S U149 (.O(n86),
	.A1(n116),
	.A2(FE_OFN64_n46),
	.B1(out_inst_2[10]),
	.B2(FE_OFN16_FE_DBTN2_n39));
   AOI22S U150 (.O(n44),
	.A1(N116),
	.A2(FE_OFN65_n46),
	.B1(out_inst_2[9]),
	.B2(FE_OFN18_FE_DBTN2_n39));
   INV1S U151 (.O(n132),
	.I(out_inst_1_15));
   NR2 U152 (.O(n43),
	.I1(FE_DBTN4_n31),
	.I2(FE_DBTN0_n56));
   INV1S U153 (.O(\add_103/A[7] ),
	.I(out_inst_1[7]));
   INV1S U154 (.O(\add_103/A[6] ),
	.I(out_inst_1[6]));
   ND3 U155 (.O(ALU_out_inst[8]),
	.I1(FE_DBTN1_n45),
	.I2(n47),
	.I3(n48));
   AOI22S U156 (.O(n48),
	.A1(N109),
	.A2(n46),
	.B1(out_inst_2[8]),
	.B2(FE_OFN16_FE_DBTN2_n39));
   INV1S U157 (.O(\add_103/A[5] ),
	.I(out_inst_1[5]));
   INV1S U158 (.O(\add_103/A[4] ),
	.I(out_inst_1[4]));
   AOI22S U159 (.O(n54),
	.A1(N108),
	.A2(n46),
	.B1(n55),
	.B2(out_inst_1[7]));
   NR2 U160 (.O(n46),
	.I1(n36),
	.I2(n132));
   INV1S U161 (.O(\add_103/A[3] ),
	.I(out_inst_1[3]));
   OAI12HS U162 (.O(n55),
	.A1(n87),
	.B1(out_inst_1_15),
	.B2(n36));
   INV1S U163 (.O(\add_103/A[2] ),
	.I(out_inst_1[2]));
   INV1S U164 (.O(\add_103/A[1] ),
	.I(out_inst_1[1]));
   INV1S U165 (.O(\add_103/A[0] ),
	.I(out_inst_1[0]));
   OAI22S U166 (.O(n92),
	.A1(n25),
	.A2(n141),
	.B1(n133),
	.B2(n26));
   NR2 U167 (.O(n35),
	.I1(n133),
	.I2(n134));
   AN2B1S U168 (.O(n25),
	.I1(n29),
	.B1(n28));
   MOAI1S U177 (.O(n50),
	.A1(out_inst_1[7]),
	.A2(n37),
	.B1(out_inst_2[7]),
	.B2(FE_OFN16_FE_DBTN2_n39));
   OAI112HS U178 (.O(n51),
	.A1(n53),
	.B1(n54),
	.C1(n52),
	.C2(FE_DBTN5_out_inst_3_7));
   OA12 U179 (.O(n52),
	.A1(n31),
	.B1(reg_data_b[7]),
	.B2(n56));
   AOI22S U180 (.O(n90),
	.A1(FE_OFN20_FE_DBTN0_n56),
	.A2(n91),
	.B1(FE_OFN15_FE_DBTN3_n37),
	.B2(\add_103/A[0] ));
   AOI22S U181 (.O(n89),
	.A1(out_inst_1[0]),
	.A2(FE_OFN63_n46),
	.B1(FE_OFN67_n55),
	.B2(out_inst_1[0]));
   AOI22S U182 (.O(n79),
	.A1(FE_OFN20_FE_DBTN0_n56),
	.A2(n80),
	.B1(FE_OFN15_FE_DBTN3_n37),
	.B2(\add_103/A[1] ));
   AOI22S U183 (.O(n78),
	.A1(N102),
	.A2(FE_OFN63_n46),
	.B1(FE_OFN67_n55),
	.B2(out_inst_1[1]));
   AOI22S U184 (.O(n75),
	.A1(FE_OFN20_FE_DBTN0_n56),
	.A2(n76),
	.B1(FE_OFN15_FE_DBTN3_n37),
	.B2(\add_103/A[2] ));
   AOI22S U185 (.O(n74),
	.A1(N103),
	.A2(FE_OFN63_n46),
	.B1(FE_OFN67_n55),
	.B2(out_inst_1[2]));
   AOI22S U186 (.O(n71),
	.A1(FE_OFN20_FE_DBTN0_n56),
	.A2(n72),
	.B1(FE_OFN15_FE_DBTN3_n37),
	.B2(\add_103/A[3] ));
   AOI22S U187 (.O(n70),
	.A1(N104),
	.A2(FE_OFN63_n46),
	.B1(FE_OFN67_n55),
	.B2(out_inst_1[3]));
   AOI22S U188 (.O(n67),
	.A1(FE_OFN20_FE_DBTN0_n56),
	.A2(n68),
	.B1(FE_OFN15_FE_DBTN3_n37),
	.B2(\add_103/A[4] ));
   AOI22S U189 (.O(n66),
	.A1(N105),
	.A2(FE_OFN63_n46),
	.B1(FE_OFN67_n55),
	.B2(out_inst_1[4]));
   AOI22S U190 (.O(n63),
	.A1(FE_OFN20_FE_DBTN0_n56),
	.A2(n64),
	.B1(FE_OFN15_FE_DBTN3_n37),
	.B2(\add_103/A[5] ));
   AOI22S U191 (.O(n62),
	.A1(N106),
	.A2(FE_OFN63_n46),
	.B1(FE_OFN67_n55),
	.B2(out_inst_1[5]));
   AOI22S U192 (.O(n59),
	.A1(FE_DBTN0_n56),
	.A2(n60),
	.B1(FE_DBTN3_n37),
	.B2(\add_103/A[6] ));
   AOI22S U193 (.O(n58),
	.A1(N107),
	.A2(n46),
	.B1(n55),
	.B2(out_inst_1[6]));
   INV1S U194 (.O(n134),
	.I(inst_i[0]));
   OAI112HS U195 (.O(n27),
	.A1(n40),
	.B1(n41),
	.C1(n38),
	.C2(n39));
   OA12 U196 (.O(n38),
	.A1(FE_OFN21_i_inst_i_2),
	.B1(inst_i[1]),
	.B2(n134));
   MAOI1 U197 (.O(n41),
	.A1(n42),
	.A2(inst_i[1]),
	.B1(n35),
	.B2(FE_OFN21_i_inst_i_2));
   ND3 U198 (.O(n40),
	.I1(n39),
	.I2(n32),
	.I3(n43));
   INV1S U199 (.O(n133),
	.I(inst_i[1]));
   MOAI1S U200 (.O(n94),
	.A1(n134),
	.A2(n26),
	.B1(n28),
	.B2(state[0]));
   OAI112HS U201 (.O(n28),
	.A1(n32),
	.B1(n33),
	.C1(n30),
	.C2(n31));
   XOR2HS U202 (.O(n30),
	.I1(n133),
	.I2(inst_i[2]));
   AOI13HS U203 (.O(n33),
	.A1(n34),
	.B1(FE_OFN21_i_inst_i_2),
	.B2(n134),
	.B3(FE_DBTN2_n39));
   OA12 U204 (.O(n34),
	.A1(FE_DBTN0_n56),
	.B1(FE_OFN21_i_inst_i_2),
	.B2(n35));
   MOAI1S U205 (.O(n93),
	.A1(n25),
	.A2(n140),
	.B1(n27),
	.B2(FE_OFN21_i_inst_i_2));
   INV1S U206 (.O(n140),
	.I(state[2]));
   ND3 U207 (.O(n31),
	.I1(state[1]),
	.I2(n140),
	.I3(state[0]));
   MOAI1S U208 (.O(n29),
	.A1(inst_i[1]),
	.A2(n134),
	.B1(n36),
	.B2(n37));
   INV1S U209 (.O(n141),
	.I(state[1]));
   ND3 U210 (.O(n56),
	.I1(state[2]),
	.I2(n141),
	.I3(state[0]));
   ND3 U211 (.O(n36),
	.I1(state[2]),
	.I2(n137),
	.I3(state[1]));
   INV1S U212 (.O(n137),
	.I(state[0]));
   NR2 U213 (.O(n42),
	.I1(inst_i[0]),
	.I2(n31));
   ND3 U214 (.O(n39),
	.I1(n137),
	.I2(n140),
	.I3(state[1]));
   ND3 U215 (.O(n87),
	.I1(n141),
	.I2(n140),
	.I3(state[0]));
   ND3 U216 (.O(n37),
	.I1(n137),
	.I2(n141),
	.I3(state[2]));
   ND3 U217 (.O(n53),
	.I1(FE_DBTN0_n56),
	.I2(FE_DBTN5_out_inst_3_7),
	.I3(reg_data_b[7]));
   NR3 U218 (.O(n49),
	.I1(state[1]),
	.I2(state[2]),
	.I3(state[0]));
   XOR2HS U220 (.O(n91),
	.I1(reg_data_b[0]),
	.I2(\reg_data_a[0] ));
   XOR2HS U221 (.O(n80),
	.I1(reg_data_b[1]),
	.I2(out_inst_3[0]));
   XOR2HS U222 (.O(n76),
	.I1(reg_data_b[2]),
	.I2(out_inst_3[1]));
   XOR2HS U223 (.O(n72),
	.I1(reg_data_b[3]),
	.I2(out_inst_3[2]));
   XOR2HS U224 (.O(n68),
	.I1(reg_data_b[4]),
	.I2(out_inst_3[3]));
   XOR2HS U225 (.O(n64),
	.I1(reg_data_b[5]),
	.I2(out_inst_3[4]));
   XOR2HS U226 (.O(n60),
	.I1(reg_data_b[6]),
	.I2(out_inst_3[5]));
   XOR2HS U229 (.O(N109),
	.I1(\add_103/carry [8]),
	.I2(n132));
   NR2 U230 (.O(N116),
	.I1(\add_103/carry [8]),
	.I2(out_inst_1_15));
endmodule

module CHIP (
	clk_p_i, 
	reset_n_i, 
	data_a_i, 
	data_b_i, 
	inst_i, 
	data_o);
   input clk_p_i;
   input reset_n_i;
   input [7:0] data_a_i;
   input [7:0] data_b_i;
   input [2:0] inst_i;
   output [15:0] data_o;

   // Internal wires
   wire FE_OFN70_i_data_o_6;
   wire FE_OFN61_n_logic1;
   wire FE_OFN60_n_logic1;
   wire FE_OFN59_n_logic1;
   wire FE_OFN58_n_logic0;
   wire FE_OFN57_n_logic0;
   wire FE_OFN56_n_logic0;
   wire FE_OFN55_n_logic0;
   wire FE_OFN54_n_logic0;
   wire FE_OFN53_n_logic0;
   wire FE_OFN52_n_logic0;
   wire FE_OFN51_n_logic0;
   wire FE_OFN50_n_logic0;
   wire FE_OFN49_n_logic0;
   wire FE_OFN48_n_logic0;
   wire FE_OFN47_n_logic0;
   wire FE_OFN46_n_logic0;
   wire FE_OFN45_n_logic0;
   wire FE_OFN44_n_logic0;
   wire FE_OFN43_n_logic0;
   wire FE_OFN42_n_logic0;
   wire FE_OFN41_n_logic0;
   wire FE_OFN40_n_logic0;
   wire FE_OFN39_n_logic0;
   wire FE_OFN38_n_logic0;
   wire FE_OFN37_n_logic0;
   wire FE_OFN36_n_logic0;
   wire FE_OFN35_n_logic0;
   wire FE_OFN34_n_logic0;
   wire FE_OFN33_n_logic0;
   wire FE_OFN32_n_logic0;
   wire FE_OFN31_n_logic0;
   wire FE_OFN22_i_data_o_7;
   wire [7:0] i_data_a_i;
   wire [7:0] i_data_b_i;
   wire [2:0] i_inst_i;
   wire [15:0] i_data_o;
   wire i_clk_p_i;
   wire i_reset_n_i;
   wire n_logic0;
   wire n_logic1;

   BUF1 FE_OFC70_i_data_o_6 (.O(FE_OFN70_i_data_o_6),
	.I(i_data_o[6]));
   BUF1 FE_OFC61_n_logic1 (.O(FE_OFN61_n_logic1),
	.I(FE_OFN60_n_logic1));
   BUF1 FE_OFC60_n_logic1 (.O(FE_OFN60_n_logic1),
	.I(n_logic1));
   BUF1 FE_OFC59_n_logic1 (.O(FE_OFN59_n_logic1),
	.I(n_logic1));
   BUF1 FE_OFC58_n_logic0 (.O(FE_OFN58_n_logic0),
	.I(FE_OFN57_n_logic0));
   BUF1 FE_OFC57_n_logic0 (.O(FE_OFN57_n_logic0),
	.I(FE_OFN56_n_logic0));
   BUF1 FE_OFC56_n_logic0 (.O(FE_OFN56_n_logic0),
	.I(FE_OFN55_n_logic0));
   BUF1 FE_OFC55_n_logic0 (.O(FE_OFN55_n_logic0),
	.I(FE_OFN54_n_logic0));
   BUF1 FE_OFC54_n_logic0 (.O(FE_OFN54_n_logic0),
	.I(FE_OFN51_n_logic0));
   BUF1 FE_OFC53_n_logic0 (.O(FE_OFN53_n_logic0),
	.I(FE_OFN50_n_logic0));
   BUF1 FE_OFC52_n_logic0 (.O(FE_OFN52_n_logic0),
	.I(FE_OFN49_n_logic0));
   BUF1 FE_OFC51_n_logic0 (.O(FE_OFN51_n_logic0),
	.I(FE_OFN48_n_logic0));
   BUF1 FE_OFC50_n_logic0 (.O(FE_OFN50_n_logic0),
	.I(FE_OFN47_n_logic0));
   BUF1 FE_OFC49_n_logic0 (.O(FE_OFN49_n_logic0),
	.I(FE_OFN46_n_logic0));
   BUF1 FE_OFC48_n_logic0 (.O(FE_OFN48_n_logic0),
	.I(FE_OFN45_n_logic0));
   BUF1 FE_OFC47_n_logic0 (.O(FE_OFN47_n_logic0),
	.I(FE_OFN44_n_logic0));
   BUF1 FE_OFC46_n_logic0 (.O(FE_OFN46_n_logic0),
	.I(FE_OFN43_n_logic0));
   BUF1 FE_OFC45_n_logic0 (.O(FE_OFN45_n_logic0),
	.I(FE_OFN42_n_logic0));
   BUF1 FE_OFC44_n_logic0 (.O(FE_OFN44_n_logic0),
	.I(FE_OFN41_n_logic0));
   BUF1 FE_OFC43_n_logic0 (.O(FE_OFN43_n_logic0),
	.I(FE_OFN40_n_logic0));
   BUF1 FE_OFC42_n_logic0 (.O(FE_OFN42_n_logic0),
	.I(FE_OFN37_n_logic0));
   BUF1 FE_OFC41_n_logic0 (.O(FE_OFN41_n_logic0),
	.I(FE_OFN36_n_logic0));
   BUF1 FE_OFC40_n_logic0 (.O(FE_OFN40_n_logic0),
	.I(FE_OFN35_n_logic0));
   INV1S FE_OFC39_n_logic0 (.O(FE_OFN39_n_logic0),
	.I(FE_OFN34_n_logic0));
   INV1S FE_OFC38_n_logic0 (.O(FE_OFN38_n_logic0),
	.I(FE_OFN34_n_logic0));
   BUF1 FE_OFC37_n_logic0 (.O(FE_OFN37_n_logic0),
	.I(FE_OFN33_n_logic0));
   BUF1 FE_OFC36_n_logic0 (.O(FE_OFN36_n_logic0),
	.I(FE_OFN32_n_logic0));
   BUF1 FE_OFC35_n_logic0 (.O(FE_OFN35_n_logic0),
	.I(FE_OFN31_n_logic0));
   INV1S FE_OFC34_n_logic0 (.O(FE_OFN34_n_logic0),
	.I(FE_OFN31_n_logic0));
   BUF1 FE_OFC33_n_logic0 (.O(FE_OFN33_n_logic0),
	.I(n_logic0));
   BUF1 FE_OFC32_n_logic0 (.O(FE_OFN32_n_logic0),
	.I(n_logic0));
   BUF1 FE_OFC31_n_logic0 (.O(FE_OFN31_n_logic0),
	.I(n_logic0));
   BUF1 FE_OFC22_i_data_o_7 (.O(FE_OFN22_i_data_o_7),
	.I(i_data_o[7]));
   alu alu_in (.clk_p_i(i_clk_p_i),
	.reset_n_i(i_reset_n_i),
	.data_a_i(i_data_a_i),
	.data_b_i(i_data_b_i),
	.inst_i(i_inst_i),
	.data_o(i_data_o));
   TIE0 ipad_n_logic0 (.O(n_logic0));
   TIE1 ipad_n_logic1 (.O(n_logic1));
   XMD ipad_clk_p_i (.O(i_clk_p_i),
	.I(clk_p_i),
	.PU(FE_OFN57_n_logic0),
	.PD(FE_OFN57_n_logic0),
	.SMT(FE_OFN56_n_logic0));
   XMD ipad_reset_n_i (.O(i_reset_n_i),
	.I(reset_n_i),
	.PU(FE_OFN56_n_logic0),
	.PD(FE_OFN56_n_logic0),
	.SMT(FE_OFN56_n_logic0));
   XMD ipad_inst_i_0 (.O(i_inst_i[0]),
	.I(inst_i[0]),
	.PU(FE_OFN55_n_logic0),
	.PD(FE_OFN56_n_logic0),
	.SMT(FE_OFN55_n_logic0));
   XMD ipad_inst_i_1 (.O(i_inst_i[1]),
	.I(inst_i[1]),
	.PU(FE_OFN55_n_logic0),
	.PD(FE_OFN55_n_logic0),
	.SMT(FE_OFN55_n_logic0));
   XMD ipad_inst_i_2 (.O(i_inst_i[2]),
	.I(inst_i[2]),
	.PU(FE_OFN54_n_logic0),
	.PD(FE_OFN54_n_logic0),
	.SMT(FE_OFN54_n_logic0));
   XMD ipad_data_a_i_0 (.O(i_data_a_i[0]),
	.I(data_a_i[0]),
	.PU(FE_OFN54_n_logic0),
	.PD(FE_OFN54_n_logic0),
	.SMT(FE_OFN51_n_logic0));
   XMD ipad_data_a_i_1 (.O(i_data_a_i[1]),
	.I(data_a_i[1]),
	.PU(FE_OFN51_n_logic0),
	.PD(FE_OFN51_n_logic0),
	.SMT(FE_OFN51_n_logic0));
   XMD ipad_data_a_i_2 (.O(i_data_a_i[2]),
	.I(data_a_i[2]),
	.PU(FE_OFN48_n_logic0),
	.PD(FE_OFN51_n_logic0),
	.SMT(FE_OFN48_n_logic0));
   XMD ipad_data_a_i_3 (.O(i_data_a_i[3]),
	.I(data_a_i[3]),
	.PU(FE_OFN48_n_logic0),
	.PD(FE_OFN48_n_logic0),
	.SMT(FE_OFN48_n_logic0));
   XMD ipad_data_a_i_4 (.O(i_data_a_i[4]),
	.I(data_a_i[4]),
	.PU(FE_OFN45_n_logic0),
	.PD(FE_OFN45_n_logic0),
	.SMT(FE_OFN45_n_logic0));
   XMD ipad_data_a_i_5 (.O(i_data_a_i[5]),
	.I(data_a_i[5]),
	.PU(FE_OFN43_n_logic0),
	.PD(FE_OFN43_n_logic0),
	.SMT(FE_OFN43_n_logic0));
   XMD ipad_data_a_i_6 (.O(i_data_a_i[6]),
	.I(data_a_i[6]),
	.PU(FE_OFN40_n_logic0),
	.PD(FE_OFN43_n_logic0),
	.SMT(FE_OFN40_n_logic0));
   XMD ipad_data_a_i_7 (.O(i_data_a_i[7]),
	.I(data_a_i[7]),
	.PU(FE_OFN40_n_logic0),
	.PD(FE_OFN40_n_logic0),
	.SMT(FE_OFN40_n_logic0));
   XMD ipad_data_b_i_0 (.O(i_data_b_i[0]),
	.I(data_b_i[0]),
	.PU(FE_OFN35_n_logic0),
	.PD(FE_OFN35_n_logic0),
	.SMT(FE_OFN35_n_logic0));
   XMD ipad_data_b_i_1 (.O(i_data_b_i[1]),
	.I(data_b_i[1]),
	.PU(FE_OFN31_n_logic0),
	.PD(FE_OFN35_n_logic0),
	.SMT(FE_OFN31_n_logic0));
   XMD ipad_data_b_i_2 (.O(i_data_b_i[2]),
	.I(data_b_i[2]),
	.PU(FE_OFN38_n_logic0),
	.PD(FE_OFN31_n_logic0),
	.SMT(FE_OFN38_n_logic0));
   XMD ipad_data_b_i_3 (.O(i_data_b_i[3]),
	.I(data_b_i[3]),
	.PU(FE_OFN39_n_logic0),
	.PD(FE_OFN39_n_logic0),
	.SMT(FE_OFN39_n_logic0));
   XMD ipad_data_b_i_4 (.O(i_data_b_i[4]),
	.I(data_b_i[4]),
	.PU(FE_OFN39_n_logic0),
	.PD(FE_OFN39_n_logic0),
	.SMT(FE_OFN39_n_logic0));
   XMD ipad_data_b_i_5 (.O(i_data_b_i[5]),
	.I(data_b_i[5]),
	.PU(FE_OFN58_n_logic0),
	.PD(FE_OFN58_n_logic0),
	.SMT(FE_OFN58_n_logic0));
   XMD ipad_data_b_i_6 (.O(i_data_b_i[6]),
	.I(data_b_i[6]),
	.PU(FE_OFN58_n_logic0),
	.PD(FE_OFN58_n_logic0),
	.SMT(FE_OFN58_n_logic0));
   XMD ipad_data_b_i_7 (.O(i_data_b_i[7]),
	.I(data_b_i[7]),
	.PU(FE_OFN57_n_logic0),
	.PD(FE_OFN57_n_logic0),
	.SMT(FE_OFN57_n_logic0));
   YA2GSD ipad_data_o_0 (.O(data_o[0]),
	.I(i_data_o[0]),
	.E(FE_OFN59_n_logic1),
	.E2(FE_OFN43_n_logic0),
	.E4(FE_OFN46_n_logic0),
	.E8(FE_OFN46_n_logic0),
	.SR(FE_OFN46_n_logic0));
   YA2GSD ipad_data_o_1 (.O(data_o[1]),
	.I(i_data_o[1]),
	.E(FE_OFN59_n_logic1),
	.E2(FE_OFN46_n_logic0),
	.E4(FE_OFN49_n_logic0),
	.E8(FE_OFN46_n_logic0),
	.SR(FE_OFN49_n_logic0));
   YA2GSD ipad_data_o_2 (.O(data_o[2]),
	.I(i_data_o[2]),
	.E(FE_OFN59_n_logic1),
	.E2(FE_OFN49_n_logic0),
	.E4(FE_OFN52_n_logic0),
	.E8(FE_OFN49_n_logic0),
	.SR(FE_OFN52_n_logic0));
   YA2GSD ipad_data_o_3 (.O(data_o[3]),
	.I(i_data_o[3]),
	.E(FE_OFN59_n_logic1),
	.E2(FE_OFN52_n_logic0),
	.E4(FE_OFN52_n_logic0),
	.E8(FE_OFN52_n_logic0),
	.SR(FE_OFN52_n_logic0));
   YA2GSD ipad_data_o_4 (.O(data_o[4]),
	.I(i_data_o[4]),
	.E(FE_OFN59_n_logic1),
	.E2(FE_OFN53_n_logic0),
	.E4(FE_OFN53_n_logic0),
	.E8(FE_OFN53_n_logic0),
	.SR(FE_OFN53_n_logic0));
   YA2GSD ipad_data_o_5 (.O(data_o[5]),
	.I(i_data_o[5]),
	.E(FE_OFN59_n_logic1),
	.E2(FE_OFN53_n_logic0),
	.E4(FE_OFN50_n_logic0),
	.E8(FE_OFN53_n_logic0),
	.SR(FE_OFN50_n_logic0));
   YA2GSD ipad_data_o_6 (.O(data_o[6]),
	.I(FE_OFN70_i_data_o_6),
	.E(FE_OFN60_n_logic1),
	.E2(FE_OFN50_n_logic0),
	.E4(FE_OFN50_n_logic0),
	.E8(FE_OFN50_n_logic0),
	.SR(FE_OFN47_n_logic0));
   YA2GSD ipad_data_o_7 (.O(data_o[7]),
	.I(FE_OFN22_i_data_o_7),
	.E(FE_OFN60_n_logic1),
	.E2(FE_OFN47_n_logic0),
	.E4(FE_OFN47_n_logic0),
	.E8(FE_OFN47_n_logic0),
	.SR(FE_OFN47_n_logic0));
   YA2GSD ipad_data_o_8 (.O(data_o[8]),
	.I(i_data_o[8]),
	.E(FE_OFN60_n_logic1),
	.E2(FE_OFN44_n_logic0),
	.E4(FE_OFN44_n_logic0),
	.E8(FE_OFN44_n_logic0),
	.SR(FE_OFN44_n_logic0));
   YA2GSD ipad_data_o_9 (.O(data_o[9]),
	.I(i_data_o[9]),
	.E(FE_OFN60_n_logic1),
	.E2(FE_OFN41_n_logic0),
	.E4(FE_OFN41_n_logic0),
	.E8(FE_OFN41_n_logic0),
	.SR(FE_OFN41_n_logic0));
   YA2GSD ipad_data_o_10 (.O(data_o[10]),
	.I(i_data_o[10]),
	.E(FE_OFN60_n_logic1),
	.E2(FE_OFN36_n_logic0),
	.E4(FE_OFN36_n_logic0),
	.E8(FE_OFN36_n_logic0),
	.SR(FE_OFN36_n_logic0));
   YA2GSD ipad_data_o_11 (.O(data_o[11]),
	.I(i_data_o[11]),
	.E(FE_OFN61_n_logic1),
	.E2(FE_OFN32_n_logic0),
	.E4(FE_OFN32_n_logic0),
	.E8(FE_OFN32_n_logic0),
	.SR(FE_OFN32_n_logic0));
   YA2GSD ipad_data_o_12 (.O(data_o[12]),
	.I(i_data_o[12]),
	.E(FE_OFN61_n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(FE_OFN33_n_logic0));
   YA2GSD ipad_data_o_13 (.O(data_o[13]),
	.I(i_data_o[13]),
	.E(FE_OFN61_n_logic1),
	.E2(FE_OFN33_n_logic0),
	.E4(FE_OFN33_n_logic0),
	.E8(FE_OFN33_n_logic0),
	.SR(FE_OFN37_n_logic0));
   YA2GSD ipad_data_o_14 (.O(data_o[14]),
	.I(i_data_o[14]),
	.E(FE_OFN61_n_logic1),
	.E2(FE_OFN37_n_logic0),
	.E4(FE_OFN37_n_logic0),
	.E8(FE_OFN37_n_logic0),
	.SR(FE_OFN42_n_logic0));
   YA2GSD ipad_data_o_15 (.O(data_o[15]),
	.I(i_data_o[15]),
	.E(FE_OFN61_n_logic1),
	.E2(FE_OFN42_n_logic0),
	.E4(FE_OFN42_n_logic0),
	.E8(FE_OFN42_n_logic0),
	.SR(FE_OFN45_n_logic0));
endmodule

