###################################################################

# Created by write_sdc on Wed Jun  5 17:14:48 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max WCCOM -max_library                               \
fsa0m_a_generic_core_ss1p62v125c\
                         -min BCCOM -min_library                               \
fsa0m_a_generic_core_ff1p98vm40c
set_wire_load_model -name G200K -library fsa0m_a_generic_core_tt1p8v25c
set_max_fanout 6 [current_design]
set_max_area 0
set_load -pin_load 10 [get_ports {o_data[20]}]
set_load -pin_load 10 [get_ports {o_data[19]}]
set_load -pin_load 10 [get_ports {o_data[18]}]
set_load -pin_load 10 [get_ports {o_data[17]}]
set_load -pin_load 10 [get_ports {o_data[16]}]
set_load -pin_load 10 [get_ports {o_data[15]}]
set_load -pin_load 10 [get_ports {o_data[14]}]
set_load -pin_load 10 [get_ports {o_data[13]}]
set_load -pin_load 10 [get_ports {o_data[12]}]
set_load -pin_load 10 [get_ports {o_data[11]}]
set_load -pin_load 10 [get_ports {o_data[10]}]
set_load -pin_load 10 [get_ports {o_data[9]}]
set_load -pin_load 10 [get_ports {o_data[8]}]
set_load -pin_load 10 [get_ports {o_data[7]}]
set_load -pin_load 10 [get_ports {o_data[6]}]
set_load -pin_load 10 [get_ports {o_data[5]}]
set_load -pin_load 10 [get_ports {o_data[4]}]
set_load -pin_load 10 [get_ports {o_data[3]}]
set_load -pin_load 10 [get_ports {o_data[2]}]
set_load -pin_load 10 [get_ports {o_data[1]}]
set_load -pin_load 10 [get_ports {o_data[0]}]
create_clock [get_ports clk]  -period 1  -waveform {0 0.5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  -max 1  [get_ports clk]
set_input_delay -clock clk  -max 1  [get_ports rst_n]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[20]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[19]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[18]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[17]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[16]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[15]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[14]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[13]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[12]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[11]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[10]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[9]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[8]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[7]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[6]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_0[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[20]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[19]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[18]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[17]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[16]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[15]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[14]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[13]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[12]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[11]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[10]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[9]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[8]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[7]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[6]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data_1[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[20]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[19]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[18]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[17]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[16]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[15]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[14]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[13]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[12]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[11]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[10]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[9]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[8]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[7]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[6]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data[0]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports rst_n]
set_drive 1  [get_ports {i_data_0[20]}]
set_drive 1  [get_ports {i_data_0[19]}]
set_drive 1  [get_ports {i_data_0[18]}]
set_drive 1  [get_ports {i_data_0[17]}]
set_drive 1  [get_ports {i_data_0[16]}]
set_drive 1  [get_ports {i_data_0[15]}]
set_drive 1  [get_ports {i_data_0[14]}]
set_drive 1  [get_ports {i_data_0[13]}]
set_drive 1  [get_ports {i_data_0[12]}]
set_drive 1  [get_ports {i_data_0[11]}]
set_drive 1  [get_ports {i_data_0[10]}]
set_drive 1  [get_ports {i_data_0[9]}]
set_drive 1  [get_ports {i_data_0[8]}]
set_drive 1  [get_ports {i_data_0[7]}]
set_drive 1  [get_ports {i_data_0[6]}]
set_drive 1  [get_ports {i_data_0[5]}]
set_drive 1  [get_ports {i_data_0[4]}]
set_drive 1  [get_ports {i_data_0[3]}]
set_drive 1  [get_ports {i_data_0[2]}]
set_drive 1  [get_ports {i_data_0[1]}]
set_drive 1  [get_ports {i_data_0[0]}]
set_drive 1  [get_ports {i_data_1[20]}]
set_drive 1  [get_ports {i_data_1[19]}]
set_drive 1  [get_ports {i_data_1[18]}]
set_drive 1  [get_ports {i_data_1[17]}]
set_drive 1  [get_ports {i_data_1[16]}]
set_drive 1  [get_ports {i_data_1[15]}]
set_drive 1  [get_ports {i_data_1[14]}]
set_drive 1  [get_ports {i_data_1[13]}]
set_drive 1  [get_ports {i_data_1[12]}]
set_drive 1  [get_ports {i_data_1[11]}]
set_drive 1  [get_ports {i_data_1[10]}]
set_drive 1  [get_ports {i_data_1[9]}]
set_drive 1  [get_ports {i_data_1[8]}]
set_drive 1  [get_ports {i_data_1[7]}]
set_drive 1  [get_ports {i_data_1[6]}]
set_drive 1  [get_ports {i_data_1[5]}]
set_drive 1  [get_ports {i_data_1[4]}]
set_drive 1  [get_ports {i_data_1[3]}]
set_drive 1  [get_ports {i_data_1[2]}]
set_drive 1  [get_ports {i_data_1[1]}]
set_drive 1  [get_ports {i_data_1[0]}]
