###################################################################

# Created by write_sdc on Wed Jun  5 16:42:08 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max WCCOM -max_library                               \
fsa0m_a_generic_core_ss1p62v125c\
                         -min BCCOM -min_library                               \
fsa0m_a_generic_core_ff1p98vm40c
set_wire_load_model -name G200K -library fsa0m_a_generic_core_tt1p8v25c
set_max_fanout 6 [current_design]
set_max_area 0
set_load -pin_load 10 [get_ports {o_weight_0[23]}]
set_load -pin_load 10 [get_ports {o_weight_0[22]}]
set_load -pin_load 10 [get_ports {o_weight_0[21]}]
set_load -pin_load 10 [get_ports {o_weight_0[20]}]
set_load -pin_load 10 [get_ports {o_weight_0[19]}]
set_load -pin_load 10 [get_ports {o_weight_0[18]}]
set_load -pin_load 10 [get_ports {o_weight_0[17]}]
set_load -pin_load 10 [get_ports {o_weight_0[16]}]
set_load -pin_load 10 [get_ports {o_weight_0[15]}]
set_load -pin_load 10 [get_ports {o_weight_0[14]}]
set_load -pin_load 10 [get_ports {o_weight_0[13]}]
set_load -pin_load 10 [get_ports {o_weight_0[12]}]
set_load -pin_load 10 [get_ports {o_weight_0[11]}]
set_load -pin_load 10 [get_ports {o_weight_0[10]}]
set_load -pin_load 10 [get_ports {o_weight_0[9]}]
set_load -pin_load 10 [get_ports {o_weight_0[8]}]
set_load -pin_load 10 [get_ports {o_weight_0[7]}]
set_load -pin_load 10 [get_ports {o_weight_0[6]}]
set_load -pin_load 10 [get_ports {o_weight_0[5]}]
set_load -pin_load 10 [get_ports {o_weight_0[4]}]
set_load -pin_load 10 [get_ports {o_weight_0[3]}]
set_load -pin_load 10 [get_ports {o_weight_0[2]}]
set_load -pin_load 10 [get_ports {o_weight_0[1]}]
set_load -pin_load 10 [get_ports {o_weight_0[0]}]
set_load -pin_load 10 [get_ports {o_weight_1[23]}]
set_load -pin_load 10 [get_ports {o_weight_1[22]}]
set_load -pin_load 10 [get_ports {o_weight_1[21]}]
set_load -pin_load 10 [get_ports {o_weight_1[20]}]
set_load -pin_load 10 [get_ports {o_weight_1[19]}]
set_load -pin_load 10 [get_ports {o_weight_1[18]}]
set_load -pin_load 10 [get_ports {o_weight_1[17]}]
set_load -pin_load 10 [get_ports {o_weight_1[16]}]
set_load -pin_load 10 [get_ports {o_weight_1[15]}]
set_load -pin_load 10 [get_ports {o_weight_1[14]}]
set_load -pin_load 10 [get_ports {o_weight_1[13]}]
set_load -pin_load 10 [get_ports {o_weight_1[12]}]
set_load -pin_load 10 [get_ports {o_weight_1[11]}]
set_load -pin_load 10 [get_ports {o_weight_1[10]}]
set_load -pin_load 10 [get_ports {o_weight_1[9]}]
set_load -pin_load 10 [get_ports {o_weight_1[8]}]
set_load -pin_load 10 [get_ports {o_weight_1[7]}]
set_load -pin_load 10 [get_ports {o_weight_1[6]}]
set_load -pin_load 10 [get_ports {o_weight_1[5]}]
set_load -pin_load 10 [get_ports {o_weight_1[4]}]
set_load -pin_load 10 [get_ports {o_weight_1[3]}]
set_load -pin_load 10 [get_ports {o_weight_1[2]}]
set_load -pin_load 10 [get_ports {o_weight_1[1]}]
set_load -pin_load 10 [get_ports {o_weight_1[0]}]
set_load -pin_load 10 [get_ports {o_weight_2[23]}]
set_load -pin_load 10 [get_ports {o_weight_2[22]}]
set_load -pin_load 10 [get_ports {o_weight_2[21]}]
set_load -pin_load 10 [get_ports {o_weight_2[20]}]
set_load -pin_load 10 [get_ports {o_weight_2[19]}]
set_load -pin_load 10 [get_ports {o_weight_2[18]}]
set_load -pin_load 10 [get_ports {o_weight_2[17]}]
set_load -pin_load 10 [get_ports {o_weight_2[16]}]
set_load -pin_load 10 [get_ports {o_weight_2[15]}]
set_load -pin_load 10 [get_ports {o_weight_2[14]}]
set_load -pin_load 10 [get_ports {o_weight_2[13]}]
set_load -pin_load 10 [get_ports {o_weight_2[12]}]
set_load -pin_load 10 [get_ports {o_weight_2[11]}]
set_load -pin_load 10 [get_ports {o_weight_2[10]}]
set_load -pin_load 10 [get_ports {o_weight_2[9]}]
set_load -pin_load 10 [get_ports {o_weight_2[8]}]
set_load -pin_load 10 [get_ports {o_weight_2[7]}]
set_load -pin_load 10 [get_ports {o_weight_2[6]}]
set_load -pin_load 10 [get_ports {o_weight_2[5]}]
set_load -pin_load 10 [get_ports {o_weight_2[4]}]
set_load -pin_load 10 [get_ports {o_weight_2[3]}]
set_load -pin_load 10 [get_ports {o_weight_2[2]}]
set_load -pin_load 10 [get_ports {o_weight_2[1]}]
set_load -pin_load 10 [get_ports {o_weight_2[0]}]
set_load -pin_load 10 [get_ports {o_data_0[47]}]
set_load -pin_load 10 [get_ports {o_data_0[46]}]
set_load -pin_load 10 [get_ports {o_data_0[45]}]
set_load -pin_load 10 [get_ports {o_data_0[44]}]
set_load -pin_load 10 [get_ports {o_data_0[43]}]
set_load -pin_load 10 [get_ports {o_data_0[42]}]
set_load -pin_load 10 [get_ports {o_data_0[41]}]
set_load -pin_load 10 [get_ports {o_data_0[40]}]
set_load -pin_load 10 [get_ports {o_data_0[39]}]
set_load -pin_load 10 [get_ports {o_data_0[38]}]
set_load -pin_load 10 [get_ports {o_data_0[37]}]
set_load -pin_load 10 [get_ports {o_data_0[36]}]
set_load -pin_load 10 [get_ports {o_data_0[35]}]
set_load -pin_load 10 [get_ports {o_data_0[34]}]
set_load -pin_load 10 [get_ports {o_data_0[33]}]
set_load -pin_load 10 [get_ports {o_data_0[32]}]
set_load -pin_load 10 [get_ports {o_data_0[31]}]
set_load -pin_load 10 [get_ports {o_data_0[30]}]
set_load -pin_load 10 [get_ports {o_data_0[29]}]
set_load -pin_load 10 [get_ports {o_data_0[28]}]
set_load -pin_load 10 [get_ports {o_data_0[27]}]
set_load -pin_load 10 [get_ports {o_data_0[26]}]
set_load -pin_load 10 [get_ports {o_data_0[25]}]
set_load -pin_load 10 [get_ports {o_data_0[24]}]
set_load -pin_load 10 [get_ports {o_data_0[23]}]
set_load -pin_load 10 [get_ports {o_data_0[22]}]
set_load -pin_load 10 [get_ports {o_data_0[21]}]
set_load -pin_load 10 [get_ports {o_data_0[20]}]
set_load -pin_load 10 [get_ports {o_data_0[19]}]
set_load -pin_load 10 [get_ports {o_data_0[18]}]
set_load -pin_load 10 [get_ports {o_data_0[17]}]
set_load -pin_load 10 [get_ports {o_data_0[16]}]
set_load -pin_load 10 [get_ports {o_data_0[15]}]
set_load -pin_load 10 [get_ports {o_data_0[14]}]
set_load -pin_load 10 [get_ports {o_data_0[13]}]
set_load -pin_load 10 [get_ports {o_data_0[12]}]
set_load -pin_load 10 [get_ports {o_data_0[11]}]
set_load -pin_load 10 [get_ports {o_data_0[10]}]
set_load -pin_load 10 [get_ports {o_data_0[9]}]
set_load -pin_load 10 [get_ports {o_data_0[8]}]
set_load -pin_load 10 [get_ports {o_data_0[7]}]
set_load -pin_load 10 [get_ports {o_data_0[6]}]
set_load -pin_load 10 [get_ports {o_data_0[5]}]
set_load -pin_load 10 [get_ports {o_data_0[4]}]
set_load -pin_load 10 [get_ports {o_data_0[3]}]
set_load -pin_load 10 [get_ports {o_data_0[2]}]
set_load -pin_load 10 [get_ports {o_data_0[1]}]
set_load -pin_load 10 [get_ports {o_data_0[0]}]
set_load -pin_load 10 [get_ports {o_data_1[47]}]
set_load -pin_load 10 [get_ports {o_data_1[46]}]
set_load -pin_load 10 [get_ports {o_data_1[45]}]
set_load -pin_load 10 [get_ports {o_data_1[44]}]
set_load -pin_load 10 [get_ports {o_data_1[43]}]
set_load -pin_load 10 [get_ports {o_data_1[42]}]
set_load -pin_load 10 [get_ports {o_data_1[41]}]
set_load -pin_load 10 [get_ports {o_data_1[40]}]
set_load -pin_load 10 [get_ports {o_data_1[39]}]
set_load -pin_load 10 [get_ports {o_data_1[38]}]
set_load -pin_load 10 [get_ports {o_data_1[37]}]
set_load -pin_load 10 [get_ports {o_data_1[36]}]
set_load -pin_load 10 [get_ports {o_data_1[35]}]
set_load -pin_load 10 [get_ports {o_data_1[34]}]
set_load -pin_load 10 [get_ports {o_data_1[33]}]
set_load -pin_load 10 [get_ports {o_data_1[32]}]
set_load -pin_load 10 [get_ports {o_data_1[31]}]
set_load -pin_load 10 [get_ports {o_data_1[30]}]
set_load -pin_load 10 [get_ports {o_data_1[29]}]
set_load -pin_load 10 [get_ports {o_data_1[28]}]
set_load -pin_load 10 [get_ports {o_data_1[27]}]
set_load -pin_load 10 [get_ports {o_data_1[26]}]
set_load -pin_load 10 [get_ports {o_data_1[25]}]
set_load -pin_load 10 [get_ports {o_data_1[24]}]
set_load -pin_load 10 [get_ports {o_data_1[23]}]
set_load -pin_load 10 [get_ports {o_data_1[22]}]
set_load -pin_load 10 [get_ports {o_data_1[21]}]
set_load -pin_load 10 [get_ports {o_data_1[20]}]
set_load -pin_load 10 [get_ports {o_data_1[19]}]
set_load -pin_load 10 [get_ports {o_data_1[18]}]
set_load -pin_load 10 [get_ports {o_data_1[17]}]
set_load -pin_load 10 [get_ports {o_data_1[16]}]
set_load -pin_load 10 [get_ports {o_data_1[15]}]
set_load -pin_load 10 [get_ports {o_data_1[14]}]
set_load -pin_load 10 [get_ports {o_data_1[13]}]
set_load -pin_load 10 [get_ports {o_data_1[12]}]
set_load -pin_load 10 [get_ports {o_data_1[11]}]
set_load -pin_load 10 [get_ports {o_data_1[10]}]
set_load -pin_load 10 [get_ports {o_data_1[9]}]
set_load -pin_load 10 [get_ports {o_data_1[8]}]
set_load -pin_load 10 [get_ports {o_data_1[7]}]
set_load -pin_load 10 [get_ports {o_data_1[6]}]
set_load -pin_load 10 [get_ports {o_data_1[5]}]
set_load -pin_load 10 [get_ports {o_data_1[4]}]
set_load -pin_load 10 [get_ports {o_data_1[3]}]
set_load -pin_load 10 [get_ports {o_data_1[2]}]
set_load -pin_load 10 [get_ports {o_data_1[1]}]
set_load -pin_load 10 [get_ports {o_data_1[0]}]
set_load -pin_load 10 [get_ports {o_data_2[47]}]
set_load -pin_load 10 [get_ports {o_data_2[46]}]
set_load -pin_load 10 [get_ports {o_data_2[45]}]
set_load -pin_load 10 [get_ports {o_data_2[44]}]
set_load -pin_load 10 [get_ports {o_data_2[43]}]
set_load -pin_load 10 [get_ports {o_data_2[42]}]
set_load -pin_load 10 [get_ports {o_data_2[41]}]
set_load -pin_load 10 [get_ports {o_data_2[40]}]
set_load -pin_load 10 [get_ports {o_data_2[39]}]
set_load -pin_load 10 [get_ports {o_data_2[38]}]
set_load -pin_load 10 [get_ports {o_data_2[37]}]
set_load -pin_load 10 [get_ports {o_data_2[36]}]
set_load -pin_load 10 [get_ports {o_data_2[35]}]
set_load -pin_load 10 [get_ports {o_data_2[34]}]
set_load -pin_load 10 [get_ports {o_data_2[33]}]
set_load -pin_load 10 [get_ports {o_data_2[32]}]
set_load -pin_load 10 [get_ports {o_data_2[31]}]
set_load -pin_load 10 [get_ports {o_data_2[30]}]
set_load -pin_load 10 [get_ports {o_data_2[29]}]
set_load -pin_load 10 [get_ports {o_data_2[28]}]
set_load -pin_load 10 [get_ports {o_data_2[27]}]
set_load -pin_load 10 [get_ports {o_data_2[26]}]
set_load -pin_load 10 [get_ports {o_data_2[25]}]
set_load -pin_load 10 [get_ports {o_data_2[24]}]
set_load -pin_load 10 [get_ports {o_data_2[23]}]
set_load -pin_load 10 [get_ports {o_data_2[22]}]
set_load -pin_load 10 [get_ports {o_data_2[21]}]
set_load -pin_load 10 [get_ports {o_data_2[20]}]
set_load -pin_load 10 [get_ports {o_data_2[19]}]
set_load -pin_load 10 [get_ports {o_data_2[18]}]
set_load -pin_load 10 [get_ports {o_data_2[17]}]
set_load -pin_load 10 [get_ports {o_data_2[16]}]
set_load -pin_load 10 [get_ports {o_data_2[15]}]
set_load -pin_load 10 [get_ports {o_data_2[14]}]
set_load -pin_load 10 [get_ports {o_data_2[13]}]
set_load -pin_load 10 [get_ports {o_data_2[12]}]
set_load -pin_load 10 [get_ports {o_data_2[11]}]
set_load -pin_load 10 [get_ports {o_data_2[10]}]
set_load -pin_load 10 [get_ports {o_data_2[9]}]
set_load -pin_load 10 [get_ports {o_data_2[8]}]
set_load -pin_load 10 [get_ports {o_data_2[7]}]
set_load -pin_load 10 [get_ports {o_data_2[6]}]
set_load -pin_load 10 [get_ports {o_data_2[5]}]
set_load -pin_load 10 [get_ports {o_data_2[4]}]
set_load -pin_load 10 [get_ports {o_data_2[3]}]
set_load -pin_load 10 [get_ports {o_data_2[2]}]
set_load -pin_load 10 [get_ports {o_data_2[1]}]
set_load -pin_load 10 [get_ports {o_data_2[0]}]
create_clock [get_ports clk]  -period 1  -waveform {0 0.5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  -max 1  [get_ports clk]
set_input_delay -clock clk  -max 1  [get_ports rst_n]
set_input_delay -clock clk  -max 1  [get_ports {layer_num[1]}]
set_input_delay -clock clk  -max 1  [get_ports {layer_num[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data[7]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data[6]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_data[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[23]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[22]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[21]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[20]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[19]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[18]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[17]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[16]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[15]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[14]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[13]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[12]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[11]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[10]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[9]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[8]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[7]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[6]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_0[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[23]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[22]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[21]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[20]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[19]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[18]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[17]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[16]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[15]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[14]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[13]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[12]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[11]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[10]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[9]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[8]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[7]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[6]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_1[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[23]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[22]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[21]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[20]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[19]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[18]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[17]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[16]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[15]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[14]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[13]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[12]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[11]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[10]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[9]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[8]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[7]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[6]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_weight_2[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[47]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[46]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[45]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[44]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[43]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[42]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[41]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[40]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[39]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[38]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[37]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[36]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[35]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[34]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[33]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[32]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[31]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[30]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[29]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[28]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[27]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[26]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[25]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[24]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[23]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[22]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[21]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[20]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[19]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[18]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[17]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[16]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[15]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[14]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[13]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[12]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[11]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[10]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[9]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[8]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[7]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[6]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_0[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[47]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[46]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[45]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[44]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[43]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[42]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[41]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[40]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[39]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[38]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[37]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[36]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[35]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[34]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[33]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[32]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[31]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[30]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[29]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[28]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[27]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[26]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[25]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[24]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[23]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[22]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[21]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[20]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[19]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[18]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[17]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[16]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[15]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[14]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[13]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[12]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[11]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[10]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[9]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[8]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[7]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[6]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_1[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[47]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[46]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[45]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[44]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[43]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[42]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[41]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[40]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[39]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[38]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[37]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[36]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[35]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[34]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[33]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[32]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[31]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[30]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[29]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[28]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[27]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[26]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[25]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[24]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[23]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[22]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[21]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[20]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[19]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[18]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[17]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[16]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[15]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[14]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[13]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[12]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[11]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[10]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[9]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[8]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[7]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[6]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_data_2[0]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports rst_n]
set_drive 1  [get_ports {layer_num[1]}]
set_drive 1  [get_ports {layer_num[0]}]
set_drive 1  [get_ports {i_data[7]}]
set_drive 1  [get_ports {i_data[6]}]
set_drive 1  [get_ports {i_data[5]}]
set_drive 1  [get_ports {i_data[4]}]
set_drive 1  [get_ports {i_data[3]}]
set_drive 1  [get_ports {i_data[2]}]
set_drive 1  [get_ports {i_data[1]}]
set_drive 1  [get_ports {i_data[0]}]
